---
abstract: "Management routines for round trip validation of users' emails"
author:
  - 'Chris Travers <chris.travers@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mail-RoundTrip
no_index:
  directory:
    - t
    - inc
requires:
  Email::Sender::Simple: 0
  Email::Simple: 0
  Email::Simple::Creator: 0
  File::Slurp: 0
  JSON: 0
  Moo: 0
  Test::Exception: 0
  Test::More: 0
  UUID::Tiny: 0
version: 0.02
